version: 2.1

orbs:
  python: circleci/python@0.2.1

jobs:
  build-and-test:
    executor: python/default
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            virtualenv ~/venv && source ~/venv/bin/activate
            pip install numpy
            pip install -r requirements.txt

workflows:
  main:
    jobs:
      - build-and-test
